#!/usr/bin/env python3
"""
Reflex Demo -- Incident Trigger Script
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Simulates the events that kick off the Reflex autonomous pipeline:

  1. Creates a GitLab issue describing the CI failure
  2. Applies the labels that Reflex monitors (reflex:incident, severity:high)
  3. Attaches pipeline context so Reflex can start its analysis

Usage (live against GitLab):
    export GITLAB_TOKEN="glpat-..."
    export GITLAB_PROJECT_ID="12345678"
    python trigger_incident.py

Usage (dry-run / demo mode -- no GitLab needed):
    python trigger_incident.py --dry-run
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone

try:
    import requests
except ImportError:
    requests = None  # dry-run mode doesn't need it

# ---------------------------------------------------------------------------
# Incident payload
# ---------------------------------------------------------------------------

INCIDENT_TITLE = (
    "[Pipeline Failure] TypeError in GET /api/users -- "
    "test_list_users_empty_db (PR #247 regression)"
)

INCIDENT_BODY = """\
## Incident Summary

**Pipeline:** #48291 on `main` -- **FAILED** at stage `test`
**Job:** `test:unit` exited with code 1
**Commit:** `a3f7c2d` -- "Optimize user listing to reduce memory allocation (PR #247)"
**Author:** @chen.wei

## Failing Test

```
FAILED tests/test_app.py::TestUsers::test_list_users_empty_db
TypeError: 'NoneType' object is not subscriptable
  File "src/demo/app.py", line 72, in list_users
    response["newest_user"] = first_user["name"]
```

## Impact

- `/api/users` returns **500** when the database has no matching users
- Dashboard user-list widget is **broken** for new tenants (empty state)
- Affects staging; blocked from deploying to production

## Expected Behavior

The endpoint should return `{"count": 0, "users": [], "newest_user": null, "newest_email": null}` when no users match the query.

## Root Cause (suspected)

PR #247 added summary stats pulled from `users[0]` without guarding against an empty result set.

---
_This incident was auto-generated by the Reflex demo trigger script._
"""

LABELS = ["reflex:incident", "severity:high", "pipeline-failure", "bug"]


# ---------------------------------------------------------------------------
# GitLab helpers
# ---------------------------------------------------------------------------

def create_gitlab_issue(project_id: str, token: str, base_url: str) -> dict:
    """Create a real GitLab issue via the API."""
    if requests is None:
        print("ERROR: 'requests' package is required for live mode.")
        print("       Install it:  pip install requests")
        sys.exit(1)

    url = f"{base_url}/api/v4/projects/{project_id}/issues"
    headers = {"PRIVATE-TOKEN": token}
    payload = {
        "title": INCIDENT_TITLE,
        "description": INCIDENT_BODY,
        "labels": ",".join(LABELS),
        "issue_type": "incident",
    }

    resp = requests.post(url, headers=headers, json=payload, timeout=15)
    resp.raise_for_status()
    return resp.json()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Trigger a Reflex demo incident")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the incident payload without calling GitLab",
    )
    parser.add_argument(
        "--gitlab-url",
        default=os.getenv("GITLAB_URL", "https://gitlab.com"),
        help="GitLab instance URL (default: https://gitlab.com)",
    )
    args = parser.parse_args()

    token = os.getenv("GITLAB_TOKEN")
    project_id = os.getenv("GITLAB_PROJECT_ID")

    print("=" * 60)
    print("  REFLEX DEMO -- Incident Trigger")
    print("=" * 60)
    print()

    if args.dry_run:
        print("[DRY RUN] Would create the following GitLab incident:\n")
        print(f"  Title:  {INCIDENT_TITLE}")
        print(f"  Labels: {', '.join(LABELS)}")
        print(f"  Time:   {datetime.now(timezone.utc).isoformat()}")
        print()
        print("--- Description ---")
        print(INCIDENT_BODY)
        print("--- End ---")
        print()
        print("[DRY RUN] No issue created. Pass a GITLAB_TOKEN and")
        print("          GITLAB_PROJECT_ID to create a real incident.")
        return

    if not token or not project_id:
        print("ERROR: Set GITLAB_TOKEN and GITLAB_PROJECT_ID environment variables.")
        print("       Or use --dry-run for demo mode.")
        sys.exit(1)

    print(f"Creating incident in project {project_id}...")
    issue = create_gitlab_issue(project_id, token, args.gitlab_url)
    print()
    print(f"  Incident created: {issue['web_url']}")
    print(f"  Issue ID:         #{issue['iid']}")
    print(f"  Labels:           {issue['labels']}")
    print()
    print("Reflex will now detect this incident and begin autonomous resolution.")
    print("Watch the pipeline for the automated fix MR.")


if __name__ == "__main__":
    main()
