"""
Jinja2-based postmortem report generator for Reflex.

Takes structured data from all six agents in the pipeline and generates
a formatted Markdown postmortem report. Outputs both a standalone file
and a GitLab issue comment-ready format.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)

try:
    from jinja2 import Environment, BaseLoader
except ImportError:
    Environment = None  # type: ignore[assignment,misc]
    BaseLoader = None  # type: ignore[assignment,misc]
    logger.warning("jinja2 not installed. Install it with: pip install jinja2")


# ---------------------------------------------------------------------------
# Jinja2 template for the Markdown postmortem
# ---------------------------------------------------------------------------

POSTMORTEM_TEMPLATE = r"""# Incident Postmortem: {{ incident_id }}

**Generated by Reflex** | {{ generated_at }}
**Severity:** {{ severity | default("Unknown") }}
**Status:** {{ status | default("Resolved") }}

---

## Timeline

| Time | Event |
|------|-------|
{% for event in timeline -%}
| {{ event.time }} | {{ event.description }} |
{% endfor %}

---

## Triage Summary

{{ triage.summary | default("No triage data available.") }}

{% if triage.initial_assessment -%}
**Initial Assessment:** {{ triage.initial_assessment }}
{% endif %}
{% if triage.affected_services -%}
**Affected Services:** {{ triage.affected_services | join(", ") }}
{% endif %}
{% if triage.priority -%}
**Priority:** {{ triage.priority }}
{% endif %}

---

## Diagnostic Findings

{% if diagnostics.log_analysis -%}
### Log Analysis

- **Errors found:** {{ diagnostics.log_analysis.error_count | default(0) }}
- **Services affected:** {{ diagnostics.log_analysis.services_affected | default([]) | join(", ") }}
{% if diagnostics.log_analysis.unique_errors -%}
- **Unique error types:**
{% for err in diagnostics.log_analysis.unique_errors %}  - {{ err }}
{% endfor %}
{% endif %}
{% endif %}

{% if diagnostics.monitoring -%}
### Monitoring Anomalies

{% for anomaly in diagnostics.monitoring.anomalies -%}
- **{{ anomaly.metric_type | default("metric") }}** on `{{ anomaly.service | default("unknown") }}`: {{ anomaly.description | default("anomaly detected") }}
{% endfor %}
{% endif %}

{% if diagnostics.stack_traces -%}
### Key Stack Traces

{% for trace in diagnostics.stack_traces %}
**{{ trace.service }}** - {{ trace.error_summary }}
```
{{ trace.stack_trace }}
```
{% endfor %}
{% endif %}

---

## Root Cause Analysis

{{ root_cause.summary | default("Root cause analysis pending.") }}

{% if root_cause.category -%}
**Category:** {{ root_cause.category }}
{% endif %}
{% if root_cause.contributing_factors -%}
**Contributing Factors:**
{% for factor in root_cause.contributing_factors %}- {{ factor }}
{% endfor %}
{% endif %}

---

## Fix Details

{{ fix.summary | default("Fix details pending.") }}

{% if fix.changes_made -%}
### Changes Made

{% for change in fix.changes_made %}- {{ change }}
{% endfor %}
{% endif %}

{% if fix.merge_request -%}
**Merge Request:** [{{ fix.merge_request.title | default("MR") }}]({{ fix.merge_request.url | default("#") }})
{% endif %}

---

## Validation

{{ validation.summary | default("Validation pending.") }}

{% if validation.checks_passed -%}
### Checks Passed

{% for check in validation.checks_passed %}- [x] {{ check }}
{% endfor %}
{% endif %}

{% if validation.checks_failed -%}
### Checks Failed

{% for check in validation.checks_failed %}- [ ] {{ check }}
{% endfor %}
{% endif %}

---

## Sustainability Impact

{% if sustainability -%}
| Metric | Reflex (Autonomous) | Human (Estimated) |
|--------|--------------------|--------------------|
| Duration | {{ sustainability.reflex_estimate.duration_hours | default(0) | round(4) }} hours | {{ sustainability.human_estimate.duration_hours | default(0) }} hours |
| Energy | {{ sustainability.reflex_estimate.energy_kwh | default(0) | round(6) }} kWh | {{ sustainability.human_estimate.energy_kwh | default(0) | round(6) }} kWh |
| Carbon | {{ sustainability.reflex_estimate.carbon_grams_co2 | default(0) | round(2) }} g CO2 | {{ sustainability.human_estimate.carbon_grams_co2 | default(0) | round(2) }} g CO2 |

**Carbon Saved:** {{ sustainability.comparison.carbon_saved_grams_co2 | default(0) | round(2) }} g CO2 ({{ sustainability.comparison.carbon_reduction_percent | default(0) | round(1) }}% reduction)
**Time Saved:** {{ sustainability.comparison.time_saved_minutes | default(0) | round(0) }} minutes

**Tokens Used:** {{ sustainability.token_usage.total | default(0) | commaformat }}
{% else -%}
_Sustainability metrics not available._
{% endif %}

---

## Recommendations

{% if recommendations -%}
{% for rec in recommendations %}- {{ rec }}
{% endfor %}
{% else -%}
_No recommendations generated yet._
{% endif %}

---

*Report generated by [Reflex](https://gitlab.com/reflex) autonomous incident pipeline.*
"""

# Compact version for GitLab issue comments (less whitespace, no table formatting).
GITLAB_COMMENT_TEMPLATE = r"""## Reflex Automated Postmortem - {{ incident_id }}

**Severity:** {{ severity | default("Unknown") }} | **Status:** {{ status | default("Resolved") }} | {{ generated_at }}

### Root Cause
{{ root_cause.summary | default("Analysis pending.") }}

### Fix Applied
{{ fix.summary | default("Fix pending.") }}
{% if fix.merge_request %}
MR: [{{ fix.merge_request.title | default("MR") }}]({{ fix.merge_request.url | default("#") }})
{% endif %}

### Sustainability
{% if sustainability -%}
Carbon saved: **{{ sustainability.comparison.carbon_saved_grams_co2 | default(0) | round(2) }} g CO2** ({{ sustainability.comparison.carbon_reduction_percent | default(0) | round(1) }}% reduction vs human response). Time saved: **{{ sustainability.comparison.time_saved_minutes | default(0) | round(0) }} min**.
{% else -%}
_Metrics not available._
{% endif %}

<details>
<summary>Full Timeline</summary>

{% for event in timeline -%}
- **{{ event.time }}** {{ event.description }}
{% endfor %}
</details>

---
*Generated by Reflex autonomous pipeline.*
"""


def _commaformat(value: Any) -> str:
    """Jinja2 filter: format a number with comma separators."""
    try:
        return f"{int(value):,}"
    except (ValueError, TypeError):
        return str(value)


class ReportGenerator:
    """
    Generates formatted Markdown postmortem reports from structured agent data.

    Uses Jinja2 templates for flexible rendering. Falls back to basic string
    formatting if Jinja2 is not installed.
    """

    def __init__(self, output_dir: Optional[str] = None) -> None:
        """
        Args:
            output_dir: Directory to write report files. Defaults to ./reports/.
        """
        self.output_dir = Path(output_dir) if output_dir else Path("reports")

        if Environment is not None and BaseLoader is not None:
            self._env = Environment(loader=BaseLoader())
            self._env.filters["commaformat"] = _commaformat
            self._postmortem_tpl = self._env.from_string(POSTMORTEM_TEMPLATE)
            self._comment_tpl = self._env.from_string(GITLAB_COMMENT_TEMPLATE)
        else:
            self._env = None
            self._postmortem_tpl = None
            self._comment_tpl = None

    def generate(
        self,
        incident_id: str,
        triage: Optional[dict[str, Any]] = None,
        diagnostics: Optional[dict[str, Any]] = None,
        root_cause: Optional[dict[str, Any]] = None,
        fix: Optional[dict[str, Any]] = None,
        validation: Optional[dict[str, Any]] = None,
        sustainability: Optional[dict[str, Any]] = None,
        timeline: Optional[list[dict[str, str]]] = None,
        severity: str = "Unknown",
        status: str = "Resolved",
        recommendations: Optional[list[str]] = None,
    ) -> str:
        """
        Generate the full Markdown postmortem report.

        Args:
            incident_id: Unique identifier for the incident.
            triage: Structured output from the triage agent.
            diagnostics: Structured output from the diagnostics agent.
            root_cause: Structured output from the root cause analysis agent.
            fix: Structured output from the fix agent.
            validation: Structured output from the validation agent.
            sustainability: Output from CarbonTracker.generate_report().
            timeline: List of {"time": ..., "description": ...} events.
            severity: Incident severity label.
            status: Current incident status.
            recommendations: List of follow-up recommendations.

        Returns:
            The rendered Markdown report as a string.
        """
        context = self._build_context(
            incident_id=incident_id,
            triage=triage,
            diagnostics=diagnostics,
            root_cause=root_cause,
            fix=fix,
            validation=validation,
            sustainability=sustainability,
            timeline=timeline,
            severity=severity,
            status=status,
            recommendations=recommendations,
        )

        if self._postmortem_tpl is not None:
            return self._postmortem_tpl.render(**context)

        return self._fallback_render(context)

    def generate_gitlab_comment(
        self,
        incident_id: str,
        triage: Optional[dict[str, Any]] = None,
        diagnostics: Optional[dict[str, Any]] = None,
        root_cause: Optional[dict[str, Any]] = None,
        fix: Optional[dict[str, Any]] = None,
        validation: Optional[dict[str, Any]] = None,
        sustainability: Optional[dict[str, Any]] = None,
        timeline: Optional[list[dict[str, str]]] = None,
        severity: str = "Unknown",
        status: str = "Resolved",
        recommendations: Optional[list[str]] = None,
    ) -> str:
        """
        Generate a compact report formatted for a GitLab issue comment.

        Same parameters as generate(). Returns a shorter Markdown string.
        """
        context = self._build_context(
            incident_id=incident_id,
            triage=triage,
            diagnostics=diagnostics,
            root_cause=root_cause,
            fix=fix,
            validation=validation,
            sustainability=sustainability,
            timeline=timeline,
            severity=severity,
            status=status,
            recommendations=recommendations,
        )

        if self._comment_tpl is not None:
            return self._comment_tpl.render(**context)

        return self._fallback_render(context, compact=True)

    def write_report(
        self,
        report_content: str,
        incident_id: str,
        suffix: str = "",
    ) -> str:
        """
        Write a report to a file.

        Args:
            report_content: The rendered Markdown content.
            incident_id: Used to name the file.
            suffix: Optional suffix before the file extension.

        Returns:
            The absolute path to the written file.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)
        safe_id = incident_id.replace("/", "_").replace(" ", "_")
        filename = f"postmortem_{safe_id}{suffix}.md"
        filepath = self.output_dir / filename

        filepath.write_text(report_content, encoding="utf-8")
        logger.info("Report written to %s", filepath.resolve())
        return str(filepath.resolve())

    @staticmethod
    def _build_context(
        incident_id: str,
        triage: Optional[dict[str, Any]] = None,
        diagnostics: Optional[dict[str, Any]] = None,
        root_cause: Optional[dict[str, Any]] = None,
        fix: Optional[dict[str, Any]] = None,
        validation: Optional[dict[str, Any]] = None,
        sustainability: Optional[dict[str, Any]] = None,
        timeline: Optional[list[dict[str, str]]] = None,
        severity: str = "Unknown",
        status: str = "Resolved",
        recommendations: Optional[list[str]] = None,
    ) -> dict[str, Any]:
        """Assemble the Jinja2 template context dict."""
        return {
            "incident_id": incident_id,
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            "severity": severity,
            "status": status,
            "timeline": timeline or [],
            "triage": triage or {},
            "diagnostics": diagnostics or {},
            "root_cause": root_cause or {},
            "fix": fix or {},
            "validation": validation or {},
            "sustainability": sustainability,
            "recommendations": recommendations or [],
        }

    @staticmethod
    def _fallback_render(context: dict[str, Any], compact: bool = False) -> str:
        """
        Basic string-based rendering when Jinja2 is not available.

        Produces a simplified but readable Markdown report.
        """
        lines = [
            f"# Incident Postmortem: {context['incident_id']}",
            "",
            f"**Generated:** {context['generated_at']}",
            f"**Severity:** {context['severity']} | **Status:** {context['status']}",
            "",
        ]

        if not compact:
            lines.append("## Timeline")
            lines.append("")
            for event in context.get("timeline", []):
                lines.append(f"- **{event.get('time', '?')}** {event.get('description', '')}")
            lines.append("")

        # Root cause
        rc = context.get("root_cause", {})
        lines.append("## Root Cause")
        lines.append(rc.get("summary", "Analysis pending."))
        lines.append("")

        # Fix
        fix = context.get("fix", {})
        lines.append("## Fix Applied")
        lines.append(fix.get("summary", "Fix pending."))
        lines.append("")

        # Sustainability
        sus = context.get("sustainability")
        if sus:
            comp = sus.get("comparison", {})
            lines.append("## Sustainability")
            lines.append(
                f"Carbon saved: {comp.get('carbon_saved_grams_co2', 0):.2f} g CO2 "
                f"({comp.get('carbon_reduction_percent', 0):.1f}% reduction)"
            )
            lines.append("")

        lines.append("---")
        lines.append("*Generated by Reflex autonomous pipeline.*")

        return "\n".join(lines)
